name: ckb-js-vm

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install llvm 18
      run: |
        sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        rm llvm.sh
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Build
      run: make all
    - name: Build qjsc
      run: make -f qjsc.mak
    - name: Install tools
      run: make install
    - name: Tests
      run: make test
    - name: Benchmark
      run: make benchmark
