name: ckb-js-std

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install llvm 18
      run: |
        sudo apt-get purge --auto-remove llvm python3-lldb-14 llvm-14
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18
        rm llvm.sh
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install tools
      run: make install
    - name: Install ckb-debugger
      run: |
        wget 'https://github.com/nervosnetwork/ckb-standalone-debugger/releases/download/v0.200.0-rc1/ckb-debugger-linux-x64.tar.gz'
        tar xzvf ckb-debugger-linux-x64.tar.gz
        mv ckb-debugger ~/.cargo/bin
    - name: Build
      run: make all
    - name: Install node dependencies
      run: pnpm install
    - name: Build all packages
      run: pnpm run build
    - name: Run examples
      run: cd packages/examples && pnpm run start && pnpm run build:simple_udt && pnpm run build:lock
    - name: Run tests
      run: pnpm test
    - name: Generate typedoc
      run: pnpm run docs
    - name: Create app
      run: cd .. && node ckb-js-vm/packages/create-app/dist/index.js test-app && cd test-app && pnpm build && pnpm test